service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs16.x #nodejs14.x   # Acá puede ser cualquier runtime, como Go, Java, Python, etc
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'  # Permitimos todo pero lo restringimos con la siguiente línea
          Resource: arn:aws:dynamodb:us-east-1:654654297903:table/usersTable
  
plugins:
  - serverless-offline
  - serverless-dynamodb

functions:              # Definimos que funciones son las que se van a ejecutar en la nube
  get-users:          # Nombre arbitrario para nuestra función
    handler: handler.getUsers    # La sintaxis es nombreArchivo.funcion
    events:                   # Definimos bajo que lógica se va a ejecutar esta lambda
      - http:
          path: users/{id}
          method: GET

custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
	
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


