service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs14.x   # Acá puede ser cualquier runtime, como Go, Java, Python, etc
  
plugins:
  - serverless-offline

functions:              # Definimos que funciones son las que se van a ejecutar en la nube
  get-users:          # Nombre arbitrario para nuestra función
    handler: handler.getUsers    # La sintaxis es nombreArchivo.funcion
    events:                   # Definimos bajo que lógica se va a ejecutar esta lambda
      - http:
          path: users
          method: GET
